### ISSUE TITLE
-all option when theres fewer reads

### ISSUE THREAD

**Issue by omarkr8** [avierstr/amplicon_sorter#9] opened 2023-01-16 02:16 UTC
at times there will be an output like:
_Comparing all reads (-a, -all) with each other is not possible when selecting more reads than available (10000 selected - 8521 available)_

I assume it is still comparing all reads? or does it then revert to random or something.
surely it should be fine to just compare all available reads even if a sample has fewer than specified?

**Comment by avierstr** [comment] 2023-01-16 09:37
You can let it compare all reads with each other by setting "-maxr 8521" for that sample. 

In your above case, it should stop en exit the program.   

1. Without that option (-a) it compares reads in batches of 1000 with each other (compares all reads in batch 1 with each other, all reads in batch 2 with each other, ... BUT it does not compare reads from batch 1 with reads from batch 2) to form groups and later it adds the remaining reads to those groups.  In the above example, there would be 9 batches.  Normally this is sufficient to analyze a data set.

2. With the "-a" option, it will use 1 batch of 8521 reads and compare all reads with each other which is time consuming.  If you select more reads (10000), it should have to compare reads with themself which is useless and for that reason it gives you that error message.

3. If you select 10000 reads from a sample with 8521 reads without the "-a" option, it will random sample 10 batches of 1000 unique reads and compare those in those batches.  This way it is possible that a read is present in batch 1 and in batch 5 so the read will be compared with 1998 other reads while in point 1 above it will only be compared with 999 other reads.

**Comment by omarkr8** [comment] 2023-01-18 04:15
thanks for confirming my suspicions. 
I ended up writing in a function to get the max reads per sample and use that for each -maxr. 
but as you say, it gets unreasonably time consuming for larger samples.

I may write in a hardcap, where it takes all reads except for cases where it exceeds 10k, in those samples just subsample 10k.
( this is for looping purposes you see)

**Comment by avierstr** [comment] 2023-01-19 11:37
It is also on my todo list to have the option just to use the max reads in a sample without specifying the number.  A hardcap may also be a good idea.

**Comment by omarkr8** [comment] 2023-01-26 02:31
agreed. I did manage to write my loop with a variable maxr. but its abit convoluted and wont work if i also use a length filter.
by adding this to a loop:
NSEQS=$( expr $(cat ${i} | wc -l) / 4 )  
-maxr ${NSEQS}

if i knew how to count read numbers AFTER length filtering, then i can use that variable instead. and my loop would be closer to what i want.

**Comment by avierstr** [comment] 2023-01-28 18:34
I have made a newer version of Amplicon_sorter (still draft and not thoroughly tested) in the draft branch: amplicon_sorter_2023_01_28.py

It has 2 extra command options:
-ar --allreads to use all reads available within the length limits.
-ldc --length_difference_consensus: Length difference between consensusses allowed to COMBINE groups based on the consensus sequence (value between 0 and 100). Default=8.0%. It is possible that you will have more than 1 group with the same sequence, but different in length (caused by incomplete PCR). By default Amplicon_sorter will keep these groups separate. If you want those groups merged for some reason, you can use this option. The consensus will probably be shorter (the average of the several lengths). Still in testing phase.

**Comment by avierstr** [comment] 2023-03-12 14:49
Fixed in version 2023_03_12

**Closed by avierstr** 2023-03-12 14:49 UTC
