### ISSUE TITLE
assigned sequences , and length difference

### ISSUE THREAD

**Issue by omarkr8** [avierstr/amplicon_sorter#8] opened 2023-01-04 05:54 UTC
Hi, 

two questions:
1) at the end of a run it'll say something like : 1201/4000 sequences assigned in groups for sampleX (30.0%)....
    where did the remaining 70% go?  is it that they failed to be merged into a group?

2) the paper for amplicon_sorter suggests that the initial length comparison looks at 5% difference. does this mean at the end, if we have two groups where one is a truncated version of the other, they will fail to merge? or does the downstream similarities ignore length differences?

very cool software, thanks.

**Comment by avierstr** [comment] 2023-01-05 14:09
Hi Omarkr8,
1. indeed, 70% failed to be assigned to a group.  Those reads should be in a file named xxx_unique.fasta.
2. it checks the length difference in every comparison.  First when comparing reads with each other, later when comparing reads with the consensus of a group.  When you have a group of reads that are a truncated version of a second group, they will not merge.  I'm planning to make that 5% parameter adjustable by the user by an extra command option in future versions.

**Comment by omarkr8** [comment] 2023-01-06 02:41
That makes sense. 
However, what if a group is a perfect nested sequence? in that other than being shorter, the remaining sequences are an exact match. I can imagine they could be merged.

**Comment by avierstr** [comment] 2023-01-06 08:01
In every comparison, a length difference of 5% is allowed.  So it will 
compare a sequence of 100 bp with one of maximum 105 bp and one of 
minimum 95 bp.  Suppose most of the reads in the group are 95 bp, the 
consensus will be 95 or 96 bp, so when it compares the consensus with 
remaining reads, it can add reads of 91 bp to the group.  So it is 
possible that the length difference in a group is more than 10% between 
the longest and shortest read.

On 6/01/2023 3:41, omarkr8 wrote:
>
> That makes sense.
> However, what if a group is a perfect nested sequence? in that other 
> than being shorter, the remaining sequences are an exact match. I can 
> imagine they could be merged.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Favierstr%2Famplicon_sorter%2Fissues%2F8%23issuecomment-1373069209&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Ccf38213de7d2489a92f708daef8f8c20%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638085697050793320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a5xqAr5xFLb6%2BRtqJu1gC7eY8if%2B6Sf9uKy4EvEWMUk%3D&reserved=0>, 
> or unsubscribe 
> <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAINKGYXFTGVALUQBRBHNFHDWQ6A6NANCNFSM6AAAAAATQNHDXM&data=05%7C01%7CAndy.Vierstraete%40ugent.be%7Ccf38213de7d2489a92f708daef8f8c20%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638085697050793320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4uTTlo6EvIG8IDenpvb6Gb1L93FdlSR4%2FtqNjEfvhDQ%3D&reserved=0>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>

-- 

********************************************************************
* “I don’t care if you’re black, white, straight, bisexual, gay,   *
* lesbian, short, tall, fat, skinny, rich or poor. If you’re nice  *
* to me, I’ll be nice to you. Simple as that.”                     *
*                                              (Robert Michaels)   *
********************************************************************


Andy Vierstraete
Department of Biology
University of Ghent
K.L.Ledeganckstraat 35
9000 Gent
Belgium
phone : 09-264 52 66
http://users.ugent.be/~avierstr
http://www.DNA.ugent.be

**Comment by omarkr8** [comment] 2023-01-18 05:06
I can see why a 5% qualifier might speed up the process. 

At the moment I am getting nested sequences split at the species group level. for example. 
s1 is 709 bp, 
s2 is 612 bp, (at 80% similarity)
s3 is 453 bp, (at 64% similarity) .

however they are perfectly nested (100% similarity where they align). s3 is a piece of s2, which is a piece of s1.
It would make sense to lump this into the same species level cluster. and I imagine your length difference parameter might allow these comparisons to be made if laxed enough. 

that said, im not entirely sure of the consequences of merging and generating a consensus with large gaps like this. i imagine the majority lengths would be used, and we may get a shorter consensus anyway.

**Comment by omarkr8** [comment] 2023-01-22 13:53
Its definitely "correct" to separate by length to start. But if there was an option to merge nested clusters, it would make metacommunity analysis a little tidier by recognizing that fragments might be nested sequences of existing clusters, rather than new species.

**Comment by avierstr** [comment] 2023-01-28 18:38
I have made a newer version of Amplicon_sorter (still draft and not thoroughly tested) in the draft branch: amplicon_sorter_2023_01_28.py

It has 2 extra command options:
-ar --allreads to use all reads available within the length limits.
-ldc --length_difference_consensus: Length difference between consensusses allowed to COMBINE groups based on the consensus sequence (value between 0 and 100). Default=8.0%. It is possible that you will have more than 1 group with the same sequence, but different in length (caused by incomplete PCR). By default Amplicon_sorter will keep these groups separate. If you want those groups merged for some reason, you can use this option. The consensus will probably be shorter (the average of the several lengths). Still in testing phase.

Can you test some of your samples with this "-ldc" option to see if it is working as expected ?  I will also do some testing, but I will have to look for good datasets to do this.

**Comment by avierstr** [comment] 2023-03-12 14:50
Fixed in version 2023_03_12

**Closed by avierstr** 2023-03-12 14:50 UTC
